import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'

for (const theme of ['light', 'dark'] as const) {
  test(`apariencia ${theme}: navegación, contraste y pantallas pequeñas`, async ({ page }, testInfo) => {
    await page.addInitScript((appearance) => {
      localStorage.setItem('ferro-settings', JSON.stringify({ state: { theme: appearance }, version: 0 }))
    }, theme)
    await page.setViewportSize({ width: 393, height: 852 })
    await page.goto('./')
    await expect(page.getByRole('heading', { name: 'Entrenar' })).toBeVisible()
    await expect(page.getByRole('navigation', { name: 'Navegación principal' }).getByRole('link')).toHaveText(['Entrenar', 'Nutrición', 'Coach', 'Progreso', 'Biblioteca'])
    await page.screenshot({ animations: 'disabled', path: testInfo.outputPath(`home-${theme}.png`) })
    if (testInfo.project.name.startsWith('chromium')) {
      const result = await new AxeBuilder({ page }).analyze()
      expect(result.violations.filter((issue) => issue.impact === 'critical' || issue.impact === 'serious')).toEqual([])
    }
    await page.getByRole('link', { name: 'Nutrición', exact: true }).click()
    await expect(page.getByRole('tab', { name: 'Diario' })).toBeVisible()
    await expect(page.getByRole('dialog')).toHaveCount(0)
    await page.screenshot({ animations: 'disabled', path: testInfo.outputPath(`nutrition-${theme}.png`) })
    await page.getByRole('link', { name: 'Perfil', exact: true }).click()
    await page.getByRole('button', { name: theme === 'light' ? 'Claro' : 'Oscuro', exact: true }).click()
    await expect(page.getByRole('dialog', { name: 'Apariencia' })).toHaveAttribute('data-state', 'open')
    await page.screenshot({ animations: 'disabled', path: testInfo.outputPath(`sheet-${theme}.png`) })
    await page.getByRole('button', { name: 'Cerrar', exact: true }).click()
    await expect(page.getByRole('dialog')).toHaveCount(0)
    await page.getByRole('link', { name: 'Biblioteca', exact: true }).click()
    await page.getByRole('searchbox', { name: 'Buscar ejercicio' }).fill('bench press')
    await expect(page.getByRole('link', { name: /barbell bench press/i }).first()).toBeVisible()
    await page.screenshot({ animations: 'disabled', path: testInfo.outputPath(`library-${theme}.png`) })
    await page.setViewportSize({ width: 320, height: 568 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await expect(page.getByRole('button', { name: 'Crear ejercicio' })).toBeVisible()
    await page.getByRole('link', { name: 'Coach', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Coach', exact: true })).toBeVisible()
    await page.getByRole('link', { name: 'Biblioteca', exact: true }).click()
    await expect(page.getByRole('searchbox', { name: 'Buscar ejercicio' })).toHaveValue('bench press')
  })
}

test('registro de series, esfuerzo y descanso con el teclado accesorio', async ({ page }, testInfo) => {
  await page.addInitScript(() => {
    localStorage.setItem('ferro-settings', JSON.stringify({ state: { theme: 'dark', trackRpe: true, trackRir: true, sound: false, vibration: false, restNotification: false, keepAwake: false }, version: 0 }))
  })
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('./')
  await page.getByRole('button', { name: 'Entrenamiento libre', exact: true }).click()
  await page.getByRole('button', { name: 'Añadir ejercicios', exact: true }).click()
  const picker = page.getByRole('dialog', { name: 'Añadir ejercicios' })
  await picker.getByRole('searchbox', { name: 'Buscar ejercicio' }).fill('barbell bench press')
  await picker.getByRole('button', { name: /barbell bench press/i }).first().click()
  await picker.getByRole('button', { name: 'Añadir 1 ejercicio', exact: true }).click()
  await expect(picker).toHaveCount(0)
  await expect(page.locator('#root')).toHaveJSProperty('inert', false)
  const weight = page.getByRole('textbox', { name: 'Peso de la serie 1 (kg)', exact: true })
  await weight.fill('40')
  await expect(weight).toHaveValue('40')
  const reps = page.getByRole('textbox', { name: 'Repeticiones de la serie 1', exact: true })
  await reps.fill('8')
  await expect(reps).toHaveValue('8')
  await expect(weight).toHaveValue('40')
  await page.getByRole('button', { name: 'Listo, terminar edición' }).click()
  await page.getByRole('button', { name: 'RPE de la serie 1', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: '8', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: 'RIR de la serie 1', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: '2', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: 'Completar serie' }).first().click()
  await expect(page.getByRole('button', { name: 'Saltar descanso' })).toBeVisible()
  await weight.focus()
  const increment = page.getByRole('button', { name: '+2.5', exact: true })
  await increment.focus()
  await increment.press('Enter')
  await expect(weight).toHaveValue('42.5')
  const keypad = await page.getByRole('group', { name: 'Ajustar peso o repeticiones' }).boundingBox()
  const rest = await page.getByRole('button', { name: 'Saltar descanso' }).boundingBox()
  expect(keypad).not.toBeNull()
  expect(rest).not.toBeNull()
  expect(rest!.y + rest!.height).toBeLessThanOrEqual(keypad!.y)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ animations: 'disabled', path: testInfo.outputPath('workout-dark-320.png') })
  await page.getByRole('button', { name: 'Listo, terminar edición' }).click()
  await expect(page.getByRole('group', { name: 'Ajustar peso o repeticiones' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Saltar descanso' }).click()
  await page.getByRole('button', { name: 'Finalizar', exact: true }).click()
  await page.getByRole('dialog', { name: 'Finalizar entreno' }).getByRole('button', { name: 'Finalizar entreno', exact: true }).click()
  await expect(page).toHaveURL(/historial\//)
  await expect(page.getByRole('link', { name: 'Progreso', exact: true })).toHaveAttribute('aria-current', 'page')
})
